# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c83d413bd308533d633b28dd3ea89fb"
application_url = "https://depot-locator-grow-declare.trycloudflare.com"
embedded = true
name = "My new awesome app"
handle = "my-new-awesome-app-205"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://depot-locator-grow-declare.trycloudflare.com/auth/callback",
  "https://depot-locator-grow-declare.trycloudflare.com/auth/shopify/callback",
  "https://depot-locator-grow-declare.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "yaroslav-vasin.myshopify.com"
automatically_update_urls_on_dev = true
